"""empty message

Revision ID: 119dbf1a529f
Revises: 42607bc73753
Create Date: 2019-04-24 11:04:03.473050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119dbf1a529f'
down_revision = '42607bc73753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ps_paciente', table_name='plano_saude_paciente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ps_paciente', 'plano_saude_paciente', ['paciente_id', 'ps_id'], unique=False)
    # ### end Alembic commands ###
