"""empty message

Revision ID: 20d846c490fc
Revises: 03cfabc8269f
Create Date: 2019-04-30 12:11:20.525824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d846c490fc'
down_revision = '03cfabc8269f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horario', sa.Column('tmp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'tmp')
    # ### end Alembic commands ###
