"""empty message

Revision ID: 3cf7ae4092ba
Revises: bb77779d73fe
Create Date: 2019-04-01 10:45:12.116839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cf7ae4092ba'
down_revision = 'bb77779d73fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paciente', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('paciente', 'dt_nascimento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('paciente', 'estado',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'filiacao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('paciente', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'paciente', ['rg'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='unique')
    op.alter_column('paciente', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('paciente', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'filiacao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'estado',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'dt_nascimento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('paciente', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('paciente', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
