"""empty message

Revision ID: 3f3fc59841d4
Revises: 3cf7ae4092ba
Create Date: 2019-04-01 13:33:51.761934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3fc59841d4'
down_revision = '3cf7ae4092ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paciente_email_key', 'paciente', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('paciente_email_key', 'paciente', ['email'])
    # ### end Alembic commands ###
