"""empty message

Revision ID: 42607bc73753
Revises: 87b7717b3d00
Create Date: 2019-04-24 11:00:39.570645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42607bc73753'
down_revision = '87b7717b3d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ps_paciente', 'plano_saude_paciente', ['paciente_id', 'ps_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ps_paciente', table_name='plano_saude_paciente')
    # ### end Alembic commands ###
