"""empty message

Revision ID: 5877f671bb47
Revises: 5b7ef310d209
Create Date: 2019-05-17 18:20:51.928144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5877f671bb47'
down_revision = '5b7ef310d209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consulta', sa.Column('cancelou', sa.Boolean(), nullable=True))
    op.add_column('consulta', sa.Column('chegou', sa.Boolean(), nullable=True))
    op.add_column('consulta', sa.Column('em_consulta', sa.Boolean(), nullable=True))
    op.add_column('consulta', sa.Column('encaixe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consulta', 'encaixe')
    op.drop_column('consulta', 'em_consulta')
    op.drop_column('consulta', 'chegou')
    op.drop_column('consulta', 'cancelou')
    # ### end Alembic commands ###
