"""empty message

Revision ID: 5b7ef310d209
Revises: 9731e479f86a
Create Date: 2019-05-14 16:34:43.273530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7ef310d209'
down_revision = '9731e479f86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('situacao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paciente', 'situacao', ['situacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='foreignkey')
    op.drop_column('paciente', 'situacao_id')
    # ### end Alembic commands ###
