"""empty message

Revision ID: 661f93df45e2
Revises: e8d20aa33ba3
Create Date: 2019-04-17 09:19:44.352948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661f93df45e2'
down_revision = 'e8d20aa33ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prontuario_legado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prontuario_legado')
    # ### end Alembic commands ###
