"""empty message

Revision ID: 715a22d982b0
Revises: 5494fc551177
Create Date: 2019-04-04 11:19:55.539663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715a22d982b0'
down_revision = '5494fc551177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('perfil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'perfil', ['perfil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'perfil_id')
    # ### end Alembic commands ###
