"""empty message

Revision ID: 81a42c2f7712
Revises: 119dbf1a529f
Create Date: 2019-04-24 11:34:54.439734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a42c2f7712'
down_revision = '119dbf1a529f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ps_paciente', 'plano_saude_paciente', ['paciente_id', 'ps_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ps_paciente', table_name='plano_saude_paciente')
    # ### end Alembic commands ###
