"""empty message

Revision ID: 87b7717b3d00
Revises: df1a744da309
Create Date: 2019-04-24 10:36:26.775311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b7717b3d00'
down_revision = 'df1a744da309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plano_saude_paciente_ps_id_key', 'plano_saude_paciente', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('plano_saude_paciente_ps_id_key', 'plano_saude_paciente', ['ps_id'])
    # ### end Alembic commands ###
