"""empty message

Revision ID: 9535d5a8606f
Revises: ba9157a81603
Create Date: 2019-05-06 10:59:35.267130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9535d5a8606f'
down_revision = 'ba9157a81603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('isEspecilista', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'isEspecilista')
    # ### end Alembic commands ###
