"""empty message

Revision ID: 9731e479f86a
Revises: a275a5f60dc5
Create Date: 2019-05-07 12:16:38.200200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9731e479f86a'
down_revision = 'a275a5f60dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('horario', sa.Column('is_encaixe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'is_encaixe')
    op.drop_table('cid')
    # ### end Alembic commands ###
