"""empty message

Revision ID: a275a5f60dc5
Revises: ab909e276fd0
Create Date: 2019-05-06 11:15:50.017922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a275a5f60dc5'
down_revision = 'ab909e276fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('is_especialista', sa.Boolean(), nullable=True))
    op.drop_column('perfil', 'is_especilista')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('is_especilista', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('perfil', 'is_especialista')
    # ### end Alembic commands ###
