"""empty message

Revision ID: ab909e276fd0
Revises: 9535d5a8606f
Create Date: 2019-05-06 11:01:29.545341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab909e276fd0'
down_revision = '9535d5a8606f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('is_especilista', sa.Boolean(), nullable=True))
    op.drop_column('perfil', 'isEspecilista')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('isEspecilista', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('perfil', 'is_especilista')
    # ### end Alembic commands ###
