"""empty message

Revision ID: ab94ede1e794
Revises: ba01c7e0f8ef
Create Date: 2019-04-19 10:14:17.948539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab94ede1e794'
down_revision = 'ba01c7e0f8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profissional', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profissional', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('profissional', 'dt_nascimento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('profissional', 'estado',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profissional', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('profissional', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profissional', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profissional', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('profissional', 'estado',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profissional', 'dt_nascimento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('profissional', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('profissional', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
