"""empty message

Revision ID: ba9157a81603
Revises: 20d846c490fc
Create Date: 2019-04-30 12:12:26.925377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9157a81603'
down_revision = '20d846c490fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horario', sa.Column('tmp', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
