"""empty message

Revision ID: c8eb7753b50a
Revises: 890e3cba623d
Create Date: 2019-04-26 10:37:47.303283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8eb7753b50a'
down_revision = '890e3cba623d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horario', sa.Column('duracao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'duracao')
    # ### end Alembic commands ###
