"""empty message

Revision ID: d79b68ccf3d7
Revises: 715a22d982b0
Create Date: 2019-04-07 10:34:57.768205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79b68ccf3d7'
down_revision = '715a22d982b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paciente_rg_key', 'paciente', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('paciente_rg_key', 'paciente', ['rg'])
    # ### end Alembic commands ###
