"""empty message

Revision ID: df1a744da309
Revises: 40aae59fea91
Create Date: 2019-04-24 09:58:18.049697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1a744da309'
down_revision = '40aae59fea91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plano_saude_paciente', ['ps_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plano_saude_paciente', type_='unique')
    # ### end Alembic commands ###
