"""empty message

Revision ID: e203e37668ac
Revises: d79b68ccf3d7
Create Date: 2019-04-11 15:05:20.477820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e203e37668ac'
down_revision = 'd79b68ccf3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profissional', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profissional', 'faculdade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'profissional', ['email'])
    op.drop_constraint('user_perfil_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'perfil_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('perfil_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_perfil_id_fkey', 'user', 'perfil', ['perfil_id'], ['id'])
    op.drop_constraint(None, 'profissional', type_='unique')
    op.alter_column('profissional', 'faculdade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profissional', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
