"""empty message

Revision ID: e8d20aa33ba3
Revises: ee6b77fa6e16
Create Date: 2019-04-16 15:14:58.627407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d20aa33ba3'
down_revision = 'ee6b77fa6e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('observacoes', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'observacoes')
    # ### end Alembic commands ###
