"""empty message

Revision ID: ee6b77fa6e16
Revises: e203e37668ac
Create Date: 2019-04-13 15:00:15.463110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee6b77fa6e16'
down_revision = 'e203e37668ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paciente', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('paciente', 'dt_nascimento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('paciente', 'estado',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'filiacao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paciente', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('paciente', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_paciente_cpf', table_name='paciente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_paciente_cpf', 'paciente', ['cpf'], unique=True)
    op.alter_column('paciente', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('paciente', 'filiacao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'estado',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paciente', 'dt_nascimento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('paciente', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('paciente', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
